server:
  port: 8082
  tomcat:
    threads:
      max: 512
      min-spare: 64
    max-connections: 2048 # 一瞬间最大支持的并发的连接数
    accept-count: 1024 # 等待队列长度

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.4:3306/im_single_chat?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    hikari:
      auto-commit: true
      #      最大连接数(使用负值表示没有限制)
      maximum-pool-size: 256
      connection-test-query: SELECT 1
      connection-timeout: 5000
      minimum-idle: 8
  redis:
    database: 0
    host: 192.168.1.4
    port: 6379
    password: redis
    timeout: 3000
    lettuce:
      pool:
        enabled: true
        max-active: 256
        max-idle: 32
        min-idle: 8
        max-wait: 5000
    address: redis://192.168.1.4:6379




im:
  token:
    secret: marding

rocketmq:
  name-server: 192.168.1.4:9876
  producer:
    group: im-message-group
    #    重试次数，加上第一次，共4次
    retry-times-when-send-failed: 3


redis:
  arrange:
    type: single # single or cluster

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html


management:
  endpoints:
    web:
      exposure:
        include: "*"
