server:
  port: 8899
  id: 1

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  #        username: nacos
  #        password: nacos
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 3000
    lettuce:
      pool:
        enabled: true
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 5000
    address: redis://localhost:6379

websocket:
  enable: true
  port: 8878
  name: ether-im-ws


rocketmq:
  name-server: localhost:9876
  producer:
    group: im-push-producer
    retry-times-when-send-failed: 3
    retry-times-when-send-async-failed: 3
    send-message-timeout: 3000
    compress-message-body-threshold: 4096

local:
  cache:
    type: guava

distribute:
  cache:
    type: redis
  lock:
    type: redisson

redis:
  arrange:
    type: single # single or cluster

logging:
  level:
    sun:
      rmi: info

