spring:
  application:
    name: im-gateway
  cloud:
    gateway:
      discovery:
        locator:
          # 是否从注册中心读取服务
          enabled: true
      routes:
        - id: im-push
          uri: ws://ether-im-ws
          predicates:
            - Path=/im/**
        - id: im-message
          uri: lb://im-message
          predicates:
            - Path=/im-message/**
        - id: im-group
          uri: lb://im-group
          predicates:
            - Path=/im-group/**
  profiles:
    active: dev
server:
  port: 8888