spring:
  application:
    name: ether-im-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        username: nacos
#        password: nacos

#  zipkin:
#    base-url: http://localhost:9411
#    sender:
#      type: web
#  sleuth:
#    sampler:
#      probability: 1.0
server:
  port: 8888